import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import './globals.css';
import Providers from '@/components/Providers';
import 'react-loading-skeleton/dist/skeleton.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// NOTA: en  la version 3 de next las rutas se crean en folders dendtro de app por ejemplo el folder de dashboard es /dashboard
// ahora deben llamrse page el index

//NOTA_2: Este poyecto trae instalado tRPC que es para que las respuestas de la api del servidor vengan tipadas, porque en un server normal las repsuesta simepre vienen con tipo :any

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <Providers>
        <body
          className={cn(
            'min-h-screen font-sans antialiased grainy',
            inter.className
          )}
        >
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
